### ISSUE TITLE
Getting exception while executing calc.feature file.

### ISSUE THREAD

**Issue by GeitRavi** [ptrthomas/karate-sikulix-demo#1] opened 2019-06-20 05:11 UTC
D:\IPS_Workspace\Java8\karate-sikulix-demo>java -cp karate.jar;sikulixapi.jar com.intuit.karate.Main calc.feature
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/IPS_Workspace/Java8/karate-sikulix-demo/karate.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/IPS_Workspace/Java8/karate-sikulix-demo/sikulixapi.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
10:37:04.056 [main] INFO  com.intuit.karate.Main - Karate version: 1.0.0
10:37:05.077 [ForkJoinPool-1-worker-1] WARN  com.intuit.karate - skipping bootstrap configuration: could not find or read file: classpath:karate-config.js
10:37:05.155 [ForkJoinPool-1-worker-1] ERROR com.intuit.karate - feature call failed: common.feature
arg: null
common.feature:6 - null
10:37:05.233 [pool-1-thread-1] INFO  com.intuit.karate.Runner - <<fail>> feature 1 of 1: calc.feature
---------------------------------------------------------
feature: calc.feature
report: target\calc.json
scenarios:  1 | passed:  0 | failed:  1 | time: 0.0687
---------------------------------------------------------
Karate version: 1.0.0
======================================================
elapsed:   1.00 | threads:    1 | thread time: 0.07
features:     1 | ignored:    0 | efficiency: 0.07
scenarios:    1 | passed:     0 | failed: 1
======================================================
failed features:
calc: -unknown-:4 -
common.feature:6 - null

Exception in thread "main" picocli.CommandLine$ExecutionException: there are test failures
        at com.intuit.karate.Main$1.handleExecutionException(Main.java:133)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:1157)
        at com.intuit.karate.Main.main(Main.java:139)

D:\IPS_Workspace\Java8\karate-sikulix-demo>

I have placed the Karate.jar & sikulxiapi.jar in same folder

**Comment by ptrthomas** [comment] 2019-06-20 12:59
@GeitRavi thanks for reporting. will be great if you can help diagnose, maybe your Java version is old.

also I updated the project - so see if the non-sikuli examples work for e.g. `java -jar karate.jar graphql.feature`

**Comment by GeitRavi** [comment] 2019-06-20 17:40
Thank you so much for your response @ptrthomas.
 
I can run graphql.feature file (java -jar karate.jar graphql.feature) successfully but to run that I have to add config SSL setting. (* configure ssl = true). 

java version "1.8.0_211".

**Comment by ptrthomas** [comment] 2019-06-21 00:21
@GeitRavi it will be nice if you provide what Java version / OS, maybe the output of `java -version`

closing as unable to reproduce. try your best to figure what is different, see if you can run this on another machine etc.

**Closed as completed by ptrthomas** 2019-06-21 00:21 UTC
Labels: help wanted
